name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: | 
        cd testunit
        chmod +x gradlew
      
    - name: Build with Gradle
      run: | 
        cd testunit
        ./gradlew clean build
    
    - name: Executar testes e gerar relatório
      run:  |
        cd testunit
        ./gradlew clean test
        # cd app
        # ls
        # pwd

    - name: Empacotar o APK
      run:  |
        cd testunit
        ./gradlew assembleDebug
      continue-on-error: true

    - name: Salvar artefatos
      uses: actions/upload-artifact@v3
      with:
        name: Relatorio de testes
        path: /home/runner/work/teste/teste/testunit/app/test-results/*
        
    - name: Salvar Pacote
      uses: actions/upload-artifact@v3
      with:
        name: Pacote APK
        path: /home/runner/work/teste/teste/testunit/app/build/outputs/apk/debug/app-debug.apk

        
    
